# Generated by Django 5.0.1 on 2024-06-21 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('email', models.CharField(max_length=66, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='کاربر فعال و اجاره ورود دارد')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر ادمین اصلی است')),
                ('is_taiid_for_shop', models.BooleanField(default=False, verbose_name='کاربر توسظ مدیر سایت تایید شده و می تواند به پنل فروشکاهی خود وارد شود ')),
                ('is_ban', models.BooleanField(default=False, verbose_name='کاربر مسدود است!')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('adress', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
