# Generated by Django 5.0.1 on 2024-06-21 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category_image/')),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Contact_to_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام ارسال کننده پیغام')),
                ('mozo', models.CharField(max_length=40, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_to_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی ارسال کننده پیام')),
                ('mozo', models.CharField(max_length=80, verbose_name='موضوع')),
                ('image', models.ImageField(upload_to='image/', verbose_name='عکس')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار این پیام')),
                ('status', models.CharField(choices=[('p', 'ارسال شود'), ('d', 'ذخیره شود بعدا ارسال می کنم')], max_length=1, verbose_name='نوع وضغیت را انتخاب کنید')),
                ('seen', models.BooleanField(default=False, verbose_name='کاربر پیغام شما را سین کرده است ')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to=settings.AUTH_USER_MODEL, verbose_name='...ارسال شود به ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('tedad', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='productimage/')),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='shop.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_panel_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shop', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('adress', models.CharField(blank=True, max_length=200)),
                ('phone_of_owner', models.CharField(blank=True, max_length=11)),
                ('phone_of_shop', models.CharField(blank=True, max_length=11)),
                ('code_melli_of_owner', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
